% Author: Joaquin Telleria (01408189)
% Visualizes data generated by the WATERLAB pipeline in form of a time series graph.
% inputs: 
% areas: a [1xN] cell of areas, where each area is a [1x1] matrix containing a single value of the final area calculated by the multi_mask_to_areas.m script
% location: a string of the geographical location of the source images.

function plot_areas(areas,location)

numberOfAreas = size(areas); % count how many areas are in the input cell 1/2
numberOfAreas = numberOfAreas(2); % count how many areas are in the input cell 2/2

x = []; % matrix for the x axis
y = []; % matrix for the y axis

x = [1:numberOfAreas]; % the x axis is a simple linear scale.

for i = 1:numberOfAreas % iterate through each area
    y = [y areas{1,i}]; % the y axis contains the value of each area
end

plot(x,y); % plot the x and y axis
title(location); % add the title
xlabel("Image"); % add the x axis label
ylabel("Water body area (squared meters)"); % add the y axis label

end
